-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2022. Máj 15. 14:35
-- Kiszolgáló verziója: 10.4.24-MariaDB
-- PHP verzió: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `webshopdb`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `felhasznalok`
--

CREATE TABLE `felhasznalok` (
  `id` int(11) NOT NULL,
  `vezeteknev` varchar(30) NOT NULL,
  `keresztnev` varchar(30) NOT NULL,
  `felhasznalonev` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `jelszo` varchar(50) NOT NULL,
  `ad` tinyint(4) NOT NULL,
  `telefonszam` varchar(11) DEFAULT NULL,
  `varos` varchar(80) DEFAULT NULL,
  `utca` varchar(80) DEFAULT NULL,
  `hazszam` varchar(8) DEFAULT NULL,
  `iranyitoszam` int(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `felhasznalok`
--

INSERT INTO `felhasznalok` (`id`, `vezeteknev`, `keresztnev`, `felhasznalonev`, `email`, `jelszo`, `ad`, `telefonszam`, `varos`, `utca`, `hazszam`, `iranyitoszam`) VALUES
(1, 'Kocsis', 'Gábor', 'admin1', 'kgabor@gmail.com', '1c37cf4f1c9ccd4f04a0378473350f01', 1, '06204964252', 'Rákócziújfalu', 'Petőfi Sándor utca', '40/a', 5084),
(2, 'Kocsis', 'Zoltán', 'kzoli', 'kzoli@gmail.com', '8af3982673455323883c06fa59d2872a', 0, NULL, NULL, NULL, NULL, NULL),
(3, 'Nánási', 'Zoltán', 'nZoli1', 'nzoltan@gmail.com', '8af3982673455323883c06fa59d2872a', 0, NULL, NULL, NULL, NULL, NULL),
(4, 'Minta', 'Béla', 'MBela1', 'minta@valami.com', '8af3982673455323883c06fa59d2872a', 0, NULL, NULL, NULL, NULL, NULL),
(5, 'Csősz', 'István', 'cspisti', 'csistvan@gmail.com', 'fd517a3ba78ca61a0c9fe3f5c50fb783', 0, NULL, 'Rákócziújfalu', 'Petőfi Sándor utca', '40', 5084);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `termekek`
--

CREATE TABLE `termekek` (
  `cikkszam` varchar(40) NOT NULL,
  `termeknev` varchar(100) NOT NULL,
  `rleiras` mediumtext NOT NULL,
  `tleiras` longtext DEFAULT NULL,
  `keszlet` int(11) NOT NULL,
  `ar` int(11) NOT NULL,
  `akcio` int(3) NOT NULL,
  `kep` varchar(255) DEFAULT NULL,
  `kategoria` varchar(40) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `termekek`
--

INSERT INTO `termekek` (`cikkszam`, `termeknev`, `rleiras`, `tleiras`, `keszlet`, `ar`, `akcio`, `kep`, `kategoria`) VALUES
('11310-01-20G', ' SAPPHIRE Radeon PULSE RX 6600 8GB GDDR6', 'Csatolófelület 	PCI-Express\nVideo chipset	AMD Radeon\nVideo chipset termékcsalád	RX 6600\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	2491 MHz\nGrafikus memória sebessége	14000 MHz\nMemória\n	\nMemória mérete 	8 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	128 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	AMD Radeon\nVideo chipset termékcsalád	RX 6600\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	2491 MHz\nGrafikus memória sebessége	14000 MHz\n\nMemória\nMemória mérete 	8 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	128 bit\nTovábbi tulajdonságok\n	\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12\nOpenGL	4.6\nTápcsatlakozó	1 x 8-pin\nFogyasztás	140 W\nAjánlott tápegység	500 W\nLite Hash Rate 	Nem\n\nAlkalmazott technológiák\n	\nAMD Eyefinity\n \nAMD HD3D\n \nAMD PowerPlay\n \nCsatlakozók	\nHDMI\nDisplayPort\n \nMéretek\n	\nSzélesség	120.1 mm\nHosszúság	193 mm\nVastagság	40.1 mm', 6, 169190, 0, '874360197.sapphire-radeon-pulse-rx-6600-8gb-gddr6-128bit-11310-01-20g.jpg', 'videokártya'),
('220-GA-0750-X2', 'EVGA SuperNOVA 5750 GA 750W', 'Tápegység típusa Moduláris tápegység\nTápegység teljesítménye	750 W\nHatásfok	80+ Gold\nPFC	Aktív\nVentilátor mérete	135 mm\nTápkapcsoló 	Van\n110V kapcsoló 	Nincs\nCsatlakozók\n	\nFDD csatlakozó 	1\nHDD csatlakozó 	4\nSATA csatlakozó 	9\nPCI-Express csatlakozó 	6', 'Egy új Gold versenyző\nAz EVGA SuperNOVA GA sorozat az EVGA kiváló tápegységeinek legújabb tagja. 80 Plus Gold tanúsítvány, 100% Japán kondenzátorok, tartós dupla golyóscsapágy, teljesen moduláris kábelezés. Ez a tápegység hosszú távú használatra és tartósságra készült. Ahogy az EVGA 80 Plus Gold minősítésű tápegységeinél megszokhattuk, a GA sorozat is kiváló funkciókat tartalmaz megfizethető áron.\n\n- 80 Plus Gold hatékonyság\n- Teljesen moduláris kábelezés\n- 100% Japán kondenzátorok\n- DC-DC átalakító, LLC áramköri kialakítás\n- Teljes elektronikai védelem\n- 10 év garancia\n- 135 mm-es ventilátor\n- Tartós dupla golyóscsapágy\n\n. ECO mód\nDedikált kapcsolóval van ellátva, a ventilátor nem pörög fel alacsony és közepes terhelés alatt. Csendesebb rendszert eredményez és a ventilátort is kíméli. ', 8, 35400, 0, '801578112.evga-supernova-5750-ga-750w-220-ga-0750-x2.jpg', 'tápegység'),
('222-00008/24/56/40', 'Microsoft Ergonomic Mouse', 'Egér típusa	Optikai\r\nVezeték nélküli	Igen\r\nEgér csatlakoztatása	Bluetooth\r\nÉrzékenység	1000 DPI\r\nGombok száma	4 db', ' . Microsoft Bluetooth Ergonomic Mouse\r\n\r\n. Ergonomikus kényelem, vezeték nélküli kialakítás\r\nEgész nap kényelmesen dolgozhat a vezeték nélküli, ergonomikus, prémium egérrel. Pontosan navigálhat a szakaszos görgetéssel, és a két programozható gombbal elérheti a leggyakrabban használt funkciókat.\r\n\r\n. Egész napos kényelem\r\nAz ergonomikus kialakítás elősegíti a semleges kéztartást.\r\n. Hosszú elemélettartam\r\nA töltöttség akár 15 hónapra is elegendő.\r\n. Max. 3 eszköz csatlakoztatható\r\nAz eszközök között zökkenőmentesen válthat.\r\n. Természetes kéztartás\r\nPuha, könnyen megfogható hüvelykujjtámasz a nagyobb kényelem érdekében.\r\n. Sima és pontos\r\nA megmunkált alumínium görgetőkerék, a teflonalap és a pontos követőérzékelő lehetővé teszi a könnyű navigációt a különböző felületeken.\r\n. Könnyű, tartós kivitel\r\nIllesztés nélküli felület, sokféle színben. ', 5, 16490, 0, '739346250.microsoft-ergonomic-mouse-222-00008-24-56-40.jpg', NULL),
('580-ADGQ', 'Dell KB216 Multimedia', 'Billentyűzet csatlakoztatása	USB\r\nVezeték nélküli	Nem\r\nMultimedia billentyűzet 	Igen\r\nHáttérvilágítás	Nincs\r\nMechanikus 	Nem\r\nNumerikus billentyűzet	Van', 'Gyártó: Dell\r\nModell: KB216 Multimedia HU (580-ADGQ)\r\n\r\nMűszaki adatok:\r\n\r\n    Típus: Szabvány\r\n    Billentyűzet felülete: USB\r\n    Technológia: Vezetékes\r\n    Csomag tartalma: Billentyűzet , USB kábel\r\n    Súly (Kg): 0.503\r\n    Egyéb: Funkció gombok , Chiclet\r\n    Méretek (mm): 442 x 24.4 x 127 mm', 5, 4690, 0, '771994452.dell-kb216-multimedia-hu-580-adgq.jpg', 'billentyűzet'),
('5JS06AA', 'HP Pavilion 800', 'Billentyűzet csatlakoztatása	USB\r\nVezeték nélküli	Nem\r\nMultimedia billentyűzet 	Igen\r\nHáttérvilágítás	Van\r\nMechanikus 	Igen\r\nNumerikus billentyűzet	Van', '', 5, 26490, 0, '922084764.hp-pavilion-800-5js06aa.jpg', 'billentyűzet'),
('920-008310', 'Logitech G413', 'Billentyűzet csatlakoztatása	USB\r\nVezeték nélküli	Nem\r\nMultimedia billentyűzet 	Igen\r\nHáttérvilágítás	Van\r\nMechanikus 	Igen\r\nNumerikus billentyűzet	Van', 'Tulajdonságok:\r\n\r\nLetisztult. Erős. Játékos.\r\nAz egyszerűség és a nagyszerűség tökéletes harmóniája.\r\nA G413 gondos tervezés, kivitelezés és mérnöki munka eredménye, hogy kiemelkedő teljesítményre legyen képes pontosan a szükséges funkciókkal. A könnyű, ugyanakkor nagy szilárdságú 5052 alumíniumötvözet burkolat teret hagy a vékony, pengeszerű alépítménynek. Alatta található egy kábelrendező egérhez és mikrofonos fejhallgatóhoz, plusz gumi stabilizálókkal ellátott állítható lábak a heves csatákhoz.\r\n\r\nRepülőipari alumíniumötvözet\r\nErő és szépség\r\nA csiszolt 5052 alumínium-magnéziumötvözetből álló felső rész alkotja a billentyűzet gerincét. Az eredmény: minimalista kialakítás teljes körű funkcionalitással párosítva. A felsőkategóriás kidolgozásra és teljesítményre koncentráló G413 a legjobb minőségű anyagokból készült.\r\n\r\nÁtmenő USB-port\r\nTöltéshez és adattovábbításhoz\r\nKényelem és sebesség elérhető közelségben. A dedikált USB-kábel külön bemenetről biztosít 100%-os tápellátást és adatátviteli sebességet az átmenő USB-port számára. Rácsatlakoztathat egy eszközt, hogy töltést biztosítson annak, vagy csatlakoztathat egy egeret, hogy egy töltettel örvendeztesse meg ellenfeleit.\r\n\r\nFejlett szolgáltatások\r\nJáték mód, 26 billentyű egyidejű érzékelése és kihagyás elleni védelem\r\nNe veszítse el a meccset csak azért, mert véletlenül lenyomja a Windows-billentyűt. Váltson játék módba az FN+F8 kombinációval. Tiltson le további gombokat az LGS használatával.\r\nNyomjon meg több gombot és módosító gombokat (Control, Alt, Shift) bármilyen sorrendben, és legyen biztos benne, hogy a kívánt eredményt éri el a 26 billentyű egyidejű érzékelésének köszönhetően.\r\nA teljesítményre hangolt kihagyás elleni védelem megbízható irányítást biztosít még akkor is, ha több játékparancsot ad ki egyszerre.\r\n\r\nRomer-G mechanikus kapcsolók:\r\n\r\n    Élettartam: 70 millió billentyűleütés\r\n    Működtetési távolság: 1,5 mm\r\n    Működtetési erő: 45 g\r\n    Teljes lenyomódási út: 3,0 mm\r\n\r\nTovábbi jellemzők:\r\n\r\n    Csatlakozás típusa: USB Type A (vezetékes)\r\n    USB-protokoll: USB 2.0\r\n    USB sebesség: teljes sebességű\r\n    Jelzőfények (LED): 2\r\n    USB-portok (beépített): 1, USB 2.0\r\n    Háttérvilágítás: vörös\r\n    Egyszínű (5 előre beállított fényerőszint)\r\n    Speciális billentyűk: Háttérvilágítás-kapcsolás: FN + F7; Játék mód: FN + F8; Médiavezérlők: FN + F9/F10/F11/F12\r\n    Kábel hossza: 1,8 m\r\n    Méret (ma x szé x mé): 132 mm x 445 mm x 34 mm\r\n    Tömeg (kábel nélkül): 1105 g\r\n', 5, 24400, 0, '815409234.logitech-g413-920-008310.jpg', ''),
('AMD-RY-3-1200-AF-4C-3100-AM4', 'AMD Ryzen 3 1200 AF 4-Core 3.1GHz АМ4 Tray', 'Típus: AMD Ryzen 3\nMagok száma: 4 magos\nSzálak száma: 4\nProcesszor foglalat: AMD Socket AM4\nProcesszor órajel: 3100 MHz\nProcesszor Turbo órajel: 3400 MHz\nGyártási technológia: 14 nm\nIntegrált grafikai processzor: Nincs\nCache\n\nL2 cache: 2 MB\nL3 cache: 8 MB\nTovábbi tulajdonságok\n\nTDP: 65 W\nKiszerelés: Tálcás', 'Gyártó: AMD\nModell: Ryzen 3 1200 AF 4-Core 3.1GHz АМ4 Tray\n\nSpecifikáció\n\n    4 mag 4 szál\n    3.1 GHz alap órajel\n    3.4 GHz max boost órajel\n    8MB L3 Cache\n    65W alap TDP\n    14 nm gyártástechnológia\n    Túlhajtható\n    AM4 tokozás\n    PCIe 3.0 támogatás\n    DDR4 2666 MHz memória támogatás, 2 memóriacsatorna\n    AMD SenseMI technológia\n    AMD \"Zen\" magarchitektúra\n    AMD VR Ready\n    AVX2, FMA3. XFR\n\nMűszaki adatok:\n\n    Foglalat: Socket AM4\n    Processzor órajel: 3.1 GHz\n    Turbo órajel (max): 3.4 GHz\n    Magok száma: 4 db\n    Feldolgozó szálak száma: 4 db\n    Csomagolás: Tálcás\n    Cache memória: 8 MB\n    Utasításkészlet: 64-bit\n    Technológia: 14 nm\n    TDP-érték: 65 W\n    Felhasználási terület: Asztali PC\n', 5, 33100, 5, '894930333.amd-ryzen-3-1200-af-4-core-3-1ghz-4-tray.jpg', 'processzor'),
('AMD-RY-5-5600X-6C-3700', 'AMD Ryzen 5 5600X 6-Core 3.7GHz AM4 Box with fan and heatsink', 'Típus	AMD Ryzen: 5 \nMagok száma: 6 magos\nSzálak száma: 12\nProcesszor foglalat: AMD Socket AM4\nProcesszor órajel: 3700 MHz\nProcesszor Turbo órajel: 4600 MHz\nGyártási technológia: 7 nm\nIntegrált grafikai processzor: Nincs\n\nCache\n	\nL2 cache: 3 MB\nL3 cache: 32 MB\nTovábbi tulajdonságok\n\nTDP: 65 W\nKiszerelés: Dobozos, hűtővel és hűtőbordával', '\nGyártó: AMD\nModell: Ryzen 5 5600X 6-Core 3.7GHz AM4\n\nMűszaki adatok:\n\n    Processzor sorozat: AMD Ryzen 5\n    Foglalat: AMD AM4\n    Mikroarchitektúra: Zen 3\n    Processzor kódnév: Vermeer\n    Hűtés típusa: Wraith Stealth\n    Processzor sorozat: AMD Ryzen 5\n    Foglalat: AMD AM4\n    Mikroarchitektúra: Zen 3\n    Processzormagok száma: 6 ×\n    Szálak száma: 12 ×\n    Processzor frekvencia: 3,7 GHz (3,7 GHz)\n    Max. frekvencia (OC): 4,6 GHz (4 600 MHz)\n    Támogatott memóriatípus: DDR4\n    Max. csatornaszám: 2 x\n    Integrált videókártya típusa: Beépített grafikus chip nélkül\n    Jellemzők: Automatikus túlpörgetés, Virtualizáció, Multi-Threading, Hűtés\n    TDP fogyasztás: 65 W\n    Gyártási technológia: 7 nm\n    L2 cache: 3 MB\n    L3 cache: 32 MB', 15, 99500, 0, '744222552.amd-ryzen-5-5600x-6-core-3-7ghz-am4-box-with-fan-and-heatsink.jpg', 'processzor'),
('AOC-24-G2U-DISP', 'AOC 24G2U Monitor ', 'Típus	LED monitor\r\nPanel típusa	IPS\r\nÍvelt kijelző	Nem\r\n3D monitor 	Nem\r\nÉrintőképernyő	Nem\r\nKépátló	23.8 inch\r\nKéparány	16:9\r\nFelbontás	1920 x 1080\r\nVálaszidő 	1 ms\r\nFényerő	250 cd/m2\r\nStatikus kontraszt 	1000:1\r\nDinamikus kontraszt	80000000:1\r\nBetekintési szög	178 °\r\nKépfrissítési frekvencia	144 Hz', 'Típus	LED monitor\r\nPanel típusa	IPS\r\nÍvelt kijelző	Nem\r\n3D monitor 	Nem\r\nÉrintőképernyő	Nem\r\nKépátló	23.8 inch\r\nKéparány	16:9\r\nFelbontás	1920 x 1080\r\nVálaszidő 	1 ms\r\nFényerő	250 cd/m2\r\nStatikus kontraszt 	1000:1\r\nDinamikus kontraszt	80000000:1\r\nBetekintési szög	178 °\r\nKépfrissítési frekvencia	144 Hz\r\nTuner\r\n	\r\nDVB-T tuner 	Nincs\r\nDVB-C tuner	Nincs\r\nHang\r\n	\r\nHangszóró	Van\r\nHangszóró teljesítménye	2 x 2 W\r\nKommunikációs csatornák\r\n	\r\nCsatlakozók	\r\nHDMI\r\nDisplayPort\r\n \r\nUSB\r\nFejhallgató\r\nMéretek és fogyasztás\r\n	\r\nSzélesség (talppal)	53.9 cm\r\nMagasság (talppal)	37.4 cm\r\nMélység (talppal)	22.7 cm\r\nTömeg (talppal)	4.3 kg\r\nEnergiaosztály - SDR (A-G) 	\r\nFogyasztás	21 W\r\nTovábbi tulajdonságok\r\n	\r\nAMD FreeSync támogatás 	Van\r\nNvidia G-Sync támogatás 	Nincs\r\nBeépített webkamera	Nincs\r\nBeépített mikrofon	Nincs', 5, 64700, 10, '613536120.aoc-24g2u.jpg', 'monitor'),
('APSO1600D3L8GB', 'CSX 8GB DDR3 1600MHz', 'Típus	Notebook memória\r\nKapacitás	8 GB\r\nKiszerelés	1x8GB\r\nMemória típusa	DDR3\r\nSebesség	1600 MHz\r\nTöbbcsatornás kiszerelés	Single-channel kiszerelés\r\nMemóriakésleltetés 	CL 9\r\nHűtőborda 	Nincs\r\nLED megvilágítás	Nincs\r\nFeszültség	1.35 V', 'Kapacitás (GB):8,\r\nÓrajel (Mhz):1600,\r\nMemória típus:DDR3 SO-DIMM L,\r\nKiszerelés (modul):1,\r\nIdõzítés (CL):Nincs adat,\r\nHűtõborda:Nem,\r\nFeszültség (V):1,35,\r\nCsomagolás:OEM, doboz nélkül,\r\n', 10, 10790, 0, '270546967.csx-8gb-ddr3-1600mhz-apso1600d3l8gb.jpg', 'notebook memória'),
('ASR-H470M-HDV', 'ASRock H470M-HDV Alaplap', 'CPU Foglalat: Socket 1200\nChipset: Intel H470\nProcesszor gyártó: Intel\nMemória típusa: DDR4\nMax. memória mérete: 64 GB\nIntegrált hangkártya: Van\nHangkártya csatorna: 7.1\nDigitális hangkimenet: Nincs\nBluetooth: Nincs\nRAID vezérlő: Nincs\nMéret szabvány: microATX', '. ASRock H470M-HDV mATX Alaplap\n\n- Támogatja a 10. generációs Intel Core Processzorokat (LGA1200)\n- Támogatja a DDR4 ramokat 2933MHz-ig\n- 1 PCIe 3.0 x16, 1 PCIe 3.0 x1\n- HDMI, D-Sub és DVI kimenet\n- 7.1 HD Audio (Realtek ALC897 Audio Codec)\n- 4 SATA3\n- 4 USB 3.2 Gen1 (2 elő- és 2 hátlapi)\n\n. 5 tápfázisú kialakítás\nRobusztus alkatrészeivel teljesen egyenletes tápellátást nyújt a CPU-nak. Emellett nagyobb a teljesítmény alacsonyabb hőmérséklet mellett, a haladó játékosoknak.\n. Prémium 50 A-es fojtótekercs a tápellátásnál\nA hagyományos fojtótekercsekhez képest az ASRock új prémium 50 A-os fojtótekercsei akár háromszor jobb telítési áramot biztosítanak, így jobb Vcore ellátás érhető el az alaplapon. ', 30, 21100, 0, '779733540.asrock-h470m-hdv.jpg', 'alaplap'),
('BHR4975EU', 'Xiaomi Mi Desktop 27', '\r\n    Felbontás: 1920 x 1080 (FHD1080) 16:9\r\n    Fényerő: 300\r\n    Gyártó: XEROX\r\n    D-Sub: Van\r\n    HDMI: Van\r\n    Panel típus: IPS\r\n    Típus: Monitor\r\n    Képarány: 16:9\r\n    Válaszidő: 6\r\n    Képátló: 27\r\n    Kontrasztarány: 1000\r\n', 'Típus	LED monitor\r\nPanel típusa	IPS\r\nÍvelt kijelző	Nem\r\n3D monitor 	Nem\r\nÉrintőképernyő	Nem\r\nKépátló	27 inch\r\nKéparány	16:9\r\nFelbontás	1920 x 1080\r\nVálaszidő 	6 ms\r\nFényerő	300 cd/m2\r\nStatikus kontraszt 	1000:1\r\nDinamikus kontraszt	1000000:1\r\nBetekintési szög	178 °\r\nKépfrissítési frekvencia	75 Hz\r\nTuner\r\n	\r\nDVB-T tuner 	Nincs\r\nDVB-C tuner	Nincs\r\nHang\r\n	\r\nHangszóró	Nincs\r\nKommunikációs csatornák\r\n	\r\nCsatlakozók	\r\nVGA (D-sub)\r\nHDMI\r\nMéretek és fogyasztás\r\n	\r\nSzélesség (talppal)	61.3 cm\r\nMagasság (talppal)	47.6 cm\r\nMélység (talppal)	20.5 cm\r\nTovábbi tulajdonságok\r\n	\r\nAMD FreeSync támogatás 	Nincs\r\nNvidia G-Sync támogatás 	Nincs\r\nBeépített webkamera	Nincs\r\nBeépített mikrofon	Nincs', 5, 54990, 0, '864013614.xiaomi-mi-desktop-27-bhr4975eu.jpg', 'monitor'),
('BL2K16G32C16U4B/R/W', 'Crucial Ballistix 32GB (2x16GB) DDR4 3200MHz', 'Típus	PC memória\r\nKapacitás	32 GB\r\nKiszerelés	2x16GB\r\nMemória típusa	DDR4\r\nSebesség	3200 MHz\r\nTöbbcsatornás kiszerelés	Dual-channel kiszerelés\r\nMemóriakésleltetés 	CL 16\r\nHűtőborda 	Van\r\nLED megvilágítás	Nincs\r\nFeszültség	1.3 V', ' Leírás:\r\n\r\nHa szenvedélyesen rajongsz a informatikai és elektromos termékekért, és szeretsz lépést tartani a technológiával, ne maradj le a legkisebb részletekről sem, vásárold meg RAM Memória Crucial BL2K16G32C16U4 32 GB DDR4 3200 Mhz-et verhetetlen áron.\r\n\r\nTulajdonságok:\r\n\r\nTechnológia: DDR4\r\nSebesség: 3200 MHz\r\nKapacitás: 32 GB (2 x 16 GB)\r\nFeszültség: 1,35 V ', 10, 57000, 10, '656813100.crucial-ballistix-32gb-2x16gb-ddr4-3200mhz-bl2k16g32c16u4b-r-w.jpg', 'memória'),
('CERBERUS-GTX1050TI-A4G', 'ASUS GeForce GTX 1050 Ti 4GB GDDR5', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	GTX 1050 Ti\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	1417 MHz\nGrafikus memória sebessége	7008 MHz\nMemória mérete 	4 GB\nMemória típusa	GDDR5\nMemória sávszélesség 	128 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	GTX 1050 Ti\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	1417 MHz\nGrafikus memória sebessége	7008 MHz\n\nMemória\n	\nMemória mérete 	4 GB\nMemória típusa	GDDR5\nMemória sávszélesség 	128 bit\n\nTovábbi tulajdonságok\n	\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12.1\nOpenGL	4.5\nTápcsatlakozó	Nincs\nAjánlott tápegység	300 W\nLite Hash Rate 	Nem\n\nAlkalmazott technológiák\n	\nnVidia CUDA \nnVidia PhysX\nnVidia Pure Video HD \nnVidia 3D Vision\n \nCsatlakozók\n	\nDVI\nHDMI \nDisplayPort\n \nMéretek\n	\nSzélesség	115 mm\nHosszúság	203 mm\nVastagság	38 mm', 15, 136125, 5, '479009039.asus-geforce-gtx-1050-ti-4gb-gddr5-128bit-cerberus-gtx1050ti-a4g.jpg', 'videokártya'),
('D-450-ADFC-MOD', 'Dell 450-ADFC 450W', 'Tápegység típusa	Flex slot\nTápegység teljesítménye	450 W', NULL, 10, 308500, 12, '919479495.dell-450-adfc-450w.jpg', 'tápegység'),
('F24T350FHR', 'Samsung F24T350FHR', 'Típus	LED monitor\r\nPanel típusa	IPS\r\nÍvelt kijelző	Nem\r\n3D monitor 	Nem\r\nÉrintőképernyő	Nem\r\nKépátló	24 inch\r\nKéparány	16:9\r\nFelbontás	1920 x 1080\r\nVálaszidő 	5 ms\r\nFényerő	250 cd/m2\r\nStatikus kontraszt 	1000:1\r\nBetekintési szög	178 °\r\nKépfrissítési frekvencia	75 Hz', ' Műszaki adatok:\r\n\r\n    Termékcsalád: Home & Office\r\n    Energia fogyasztás: 25 W\r\n    Súly: 2.7 kg\r\n    Hosszúság: 539.2 mm\r\n    Szélesség: 232 mm\r\n    Magasság: 425.3 mm\r\n    Energiafogyasztás / 1000 óra: 16 kWh\r\n    Energiahatékonyság a legújabb európai előírások szerint E energiaosztály\r\n\r\nKijelző\r\n\r\n    Átmérő: 23.8 inch\r\n    Kijelző technológiája: IPS\r\n    Felbontás típus: Full HD\r\n    Optimális felbontás: 1920 x 1080\r\n    Háttérvilágítás típus: LED\r\n    Képarány: 16:9\r\n    Képernyő formátum: Wide\r\n    Kijelző felületének típusa: Tükröződésmentes\r\n    Fényerő: 250 cd/mp\r\n    Válaszidő: 5 ms (GtG)\r\n    Látószög Vízszintes/Függőleges: 178°/178°\r\n    Jellemző kontraszt: 1000:1‎\r\n    Dinamikus kontraszt: Mega\r\n    Maximális frissítési frekvencia: 75 Hz\r\n    Színek száma: 16,7 millió\r\n\r\nCsatlakozás\r\n\r\n    Video portok: 1 x HDMI , 1 x D-sub\r\n\r\nFelszerelések\r\n\r\n    Speciális funkciók: Ergonómia , Kensington Lock\r\n    Falra szerelés VESA 100 x 100 mm\r\n    Technológiák: Game Mode , Off Timer Plus , Flicker Free , Eye Saver Mode , Eco Saving Plus , AMD FreeSync™ , Image Size\r\n    Csomag tartalma: 1 x Tápkábel , 1 x Monitor , 1 x CD illesztőprogramokkal , 1 x HDMI-DVI kábel\r\n\r\nErgonómia\r\n\r\n    Dönthető: -2° +20°\r\n\r\nTuner\r\n	\r\nDVB-T tuner 	Nincs\r\nDVB-C tuner	Nincs\r\nHang\r\n	\r\nHangszóró	Nincs\r\nKommunikációs csatornák\r\n	\r\nCsatlakozók	\r\nVGA (D-sub)\r\nHDMI\r\nMéretek és fogyasztás\r\n	\r\nSzélesség (talppal)	53.9 cm\r\nMagasság (talppal)	42.5 cm\r\nMélység (talppal)	23.2 cm\r\nTömeg (talppal)	2.7 kg\r\nEnergiaosztály - SDR (A-G) 	\r\nTermékinformációs adatlap\r\nFogyasztás	25 W\r\nTovábbi tulajdonságok\r\n	\r\nAMD FreeSync támogatás 	Van\r\nNvidia G-Sync támogatás 	Nincs\r\nBeépített webkamera	Nincs\r\nBeépített mikrofon	Nincs', 5, 50290, 10, '799547373.samsung-f24t350fhr.jpg', 'monitor'),
('GBE-B660M-DS3H', 'GIGABYTE B660M DS3H DDR4 Alaplap', 'CPU Foglalat: Socket 1700\nChipset: Intel B660\nProcesszor gyártó: Intel\nMemória típusa:	DDR4\nMax. memória mérete: 128 GB\nIntegrált hangkártya: Van\nHangkártya csatorna: 7.1\nBluetooth: Nincs\nRAID vezérlő: Van\nMéret szabvány: microATX', 'Gyártó: GIGABYTE\nModell: B660M DS3H DDR4\n\nMűszaki adatok:\n\nFoglalat és lapkakészlet\n\n    Foglalat: Intel LGA1700\n    Lapkakészlet: Intel B660\n\nFormátum & funkciók\n\n    Alaplap formátum: mATX (Micro ATX)\n    Alapvető funkciók: Integrált hálózati kártya, Integrált hangkártya, M.2 , PCI Express 4.0, CPU hely integrált GPU-val, Serial ATA III\n\nRendszermemória\n\n    Kivitelezés: DIMM\n    Memória típusa: DDR4\n    RAM slotok száma: 4 ×\n    Csatlakozás mód: Dual-channel\n    Max. frekvencia (OC): 3 200 MHz\n\nFejlett paraméterek\n\n    Hangkártya típusa: Realtek ALC897\n    Hangkártya-csatornák száma: 8\n\nCsatlakozók\n\n    Külső: DisplayPort, HDMI, Jack, PS/2, RJ-45 (LAN) 2.5Gbps, USB 2.0, USB 3.2 Gen 1 (USB 3.0), USB 3.2 Gen 2, USB-C, VGA (D-Sub)\n    Belső: ARGB LED Header, COM header, LPT header, M2 foglalat, RGB LED Header, S/PDIF header, Serial-ATA-III, TPM header, USB 2.0 header, USB 3.2 Gen 1 bracket\n    PCI Express x16: 1×\n    PCI express x1: 2×\n    M.2 slotok: 2×\n    USB 2.0: 2×\n    USB 3.2 Gen 1 (USB 3.0): 3×\n    USB 3.1 (3.1 gen2): 1×\n    Serial ATA III: 4×\n', 20, 46070, 0, '920952510.gigabyte-b660m-ds3h-ddr4.jpg', 'alaplap'),
('GV-N166TOC-6GD', ' GIGABYTE GeForce GTX 1660 Ti OC 6GB', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	GTX 1660 Ti\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	1800 MHz\nGrafikus memória sebessége	12000 MHz\nMemória mérete 	6 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	192 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	GTX 1660 Ti\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	1800 MHz\nGrafikus memória sebessége	12000 MHz\n\nMemória\n	\nMemória mérete 	6 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	192 bit\n\nTovábbi tulajdonságok\n	\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12\nOpenGL	4.5\nTápcsatlakozó	1 x 8-pin\nAjánlott tápegység	450 W\nLite Hash Rate 	Nem\n\nAlkalmazott technológiák\n\nnVidia CUDA \nnVidia PhysX\nnVidia Pure Video HD\nnVidia 3D Vision\nGeForce GTX VR Ready\n \nCsatlakozók\n\nHDMI \nDisplayPort\n \nMéretek\n	\nSzélesség	122 mm\nHosszúság	225.7 mm\nVastagság	40.5 mm', 15, 166243, 12, '558445815.gigabyte-geforce-gtx-1660-ti-oc-6gb-gv-n166toc-6gd.jpg', 'videokártya'),
('HP-Q-P1000-1ME01AA', 'HP Quadro P1000 4GB', 'Hűtés típusa 	Aktív hűtés\nVentilátorok száma	1 darab\nGrafikus chip sebessége	1455 MHz\nMemória\nMemória mérete 	4 GB\nMemória típusa	GDDR5\nMemória sávszélesség 	128 bit', 'Teljes körű professzionális grafikai teljesítményt nyújt a 3D modellekhez és 2D képi megjelenítéshez, valamint támogatást nyújt az NVIDIA® Quadro® P1000 NVIDIA Pascal GPU technológiával működő, legfeljebb négy 4K kijelzővel rendelkező, kiterjedt vizuális munkaterületéhez.\r\n\r\nMunka és interakció több alkalmazással és nagy modellekkel, jelenetekkel, tervekkel és szerelvényekkel, elakadhatatlanul valós időben, a dedikált 4 GB-os GDDR5 memóriában tárolt eszközöket érheti el.\r\n\r\nNagy fényerejű és színtelítettségű, 10K: 1 CR fölött, valamint akár a 4db 4K kijelző vagy egy DisplayPort 1.4 kijelzővel ellátott 5K kijelző támogatása. Könnyen kezelheti a beállításokat az NVIDIA® nView® segítségével. HDR video létrehozása és lejátszása H. 264 és HEVC motorokkal.\r\n\r\nTámogatja az OpenGL, a DirectX, a Vulkan és az NVIDIA® CUDA legújabb kiadásait, így biztosítva a gyakran használt professzionális alkalmazásokkal való kompatibilitást.\r\n\r\nKompatibilis a HP Z240 torony, a Z240 kis formájú tényezővel és a Z440 munkaállomásokkal. ', 12, 132200, 15, '464613983.hp-quadro-p1000-4gb-1me01aa.jpg', 'videokártya'),
('HP-R7-5JW82AA', 'HP Radeon R7 430 2GB GDDR5', 'Csatolófelület 	PCI-Express\r\nVideo chipset	AMD Radeon\r\nHűtés típusa 	Aktív hűtés\r\nVentilátorok száma	1 darab\r\nMemória mérete 	2 GB\r\nMemória típusa	GDDR5\r\nCsatlakozók DisplayPort ', '', 10, 42680, 0, '726071316.hp-radeon-r7-430-2gb-gddr5-5jw82aa.jpg', 'videokártya'),
('INT-I5-10400F-6C-2900-LGA1200', 'Intel Core i5-10400F 6-Core 2.9GHz LGA1200 Box (EN)', 'Típus: Intel Core i5\nMagok száma:6 magos\nSzálak száma:12\nProcesszor foglalat: Intel Socket 1200\nProcesszor órajel:2900 MHz\nProcesszor Turbo órajel: 4300 MHz\nGyártási technológia: 14 nm\nIntegrált grafikai processzor: Nincs\nDMI sebesség: 8 GT/s\nCache\n	\nL3 cache:12 MB\nTovábbi tulajdonságok\n\nTDP: 65 W\nKiszerelés: Dobozos', 'Gyártó: Intel\nModell: Core i5-10400F 6-Core 2.9GHz LGA1200\n\nLeírás:\n\nA frekvencia, a magok és a szálak optimális egyensúlyával, fejlett tuningolási támogatással, és kimagasló csatlakoztathatósággal az új 10. generációs Intel Core processzorok segítenek az asztali PC-k felturbózásában, és hihetetlen élményeket és termelékenységet tesznek lehetővé a játékosok, a tartalomkészítők és a hétköznapi felhasználók számára.\n\nDöntsd le a teljesítménybeli akadályt, és lépj be a magával ragadó 4K szórakoztató élmények birodalmába, és játssz a legújabb játékcímekkel úgy, mint még soha. Vagy egyszerűen csak végezze el a munkát kevesebb idő alatt a legújabb üzleti termelékenységi alkalmazások felgyorsításával a magasabb szintű együttműködés és termelékenység érdekében.\n\nAkár kiváló teljesítményt keres, akár csak a túlhajtás előnyeit szeretné élvezni, van egy új 10. generációs Intel Core processzor az Ön számára. ', 15, 48200, 0, '685923909.intel-core-i5-10400f-6-core-2-9ghz-lga1200-box-en.jpg', 'processzor'),
('INT-I5-12400F-6C-2500-LGA1700', 'Intel i5-12400F 6-Core 2.50GHz LGA1700 Box', 'Típus: Intel Core i5\nMagok száma: 6 magos\nSzálak száma: 12\nProcesszor foglalat: Intel Socket 1700\nProcesszor órajel: 2500 MHz\nProcesszor Turbo órajel: 4400 MHz\nGyártási technológia: 10 nm\nIntegrált grafikai processzor:Nincs\nCache\nL2 cache: 7.5 MB\nL3 cache: 18 MB\n\nTovábbi tulajdonságok\n	\nTDP: 65 W\nKiszerelés:Dobozos', 'Gyártó: Intel\nModell: i5-12400F 6-Core 2.50GHz LGA1700 Box\n\nMűszaki adatok:\n\n    Processzor sorozat: Intel Core i5\n    Foglalat: Intel LGA1700\n    Modellmegjelölés: Intel Core i5-12400F\n    Mikroarchitektúra: Golden Cove, Gracemont\n    Processzor kódnév: Alder Lake-S\n    Hűtés típusa: RM1\n    Processzormagok száma: 6 ×\n    Szálak száma: 12 ×\n    Processzor frekvencia: 2,5 GHz (2,5 GHz)\n    Max. frekvencia (OC): 4,4 GHz (4 400 MHz)\n    Támogatott memóriatípus: DDR4/DDR5\n    Max. csatornaszám: 2 ×\n    CPU Passmark: 17 437\n    Jellemzők: Automatikus túlpörgetés, Virtualizáció, Multi-Threading, Hűtés\n    TDP fogyasztás: 117 W\n    L2 cache: 7,5 MB\n    L3 cache: 18 MB\n', 5, 78900, 5, '915286329.intel-i5-12400f-6-core-2-50ghz-lga1700-box.jpg', 'processzor'),
('KF432C16BBK2/16', 'Kingston FURY Beast 16GB (2x8GB) DDR4 3200MHz', 'Típus	PC memória\r\nKapacitás	16 GB\r\nKiszerelés	2x8GB\r\nMemória típusa	DDR4\r\nSebesség	3200 MHz\r\nTöbbcsatornás kiszerelés	Dual-channel kiszerelés\r\nMemóriakésleltetés 	CL 16\r\nHűtőborda 	Van\r\nLED megvilágítás	Nincs\r\nFeszültség	1.35 V', 'Kingston FURY Beast DDR4 memória\r\n\r\nA Kingston FURY™ Beast DDR4 memória erőteljes teljesítménynövekedést kínál a játékhoz, videószerkesztéshez és rendereléshez, akár 3733 MHz-es sebességgel. Ez a költséghatékony frissítés 2666MHz-3733MHz sebességgel, CL15-19 késleltetéssel, 4GB-32GB egymodulos kapacitással és 8GB-128GB készletkapacitással érhető el. Automatikus Plug N Play túlhajtással rendelkezik 2666 MHz-en, és Intel XMP- és AMD Ryzen™-képes. A FURY Beast DDR4 a karcsú, alacsony profilú hőelosztónak köszönhetően hűvös marad. A 100%-ban sebességtesztelt és élettartam- garanciával támogatott termék egyszerű és gondtalan frissítést jelent Intel- vagy AMD-alapú rendszeréhez.\r\n\r\nAlacsony profilú hőszóró\r\n\r\nAz új, elegáns megjelenésű radiátor nagyszerű frissítés a harci állomás stílusához.\r\n\r\nNagy teljesítményű, költséghatékony upgrade\r\n\r\nA Kingston FURY Beast DDR4 tökéletes választás a rendszerépítőknek vagy azoknak, akik frissítést keresnek lassú rendszerük beindításához.\r\n\r\nIntel XMP-kész\r\n\r\nMérnökeink előre definiált Intel Extreme Memory Profilokat terveztek, hogy maximalizálják a memóriamodulok teljesítményét, amelyek akár 3733 MHz-es sebességet is elérhetnek.\r\n\r\nKészen áll az AMD Ryzen™ rendszerre\r\n\r\nSzerezzen be Ryzen-képes memóriát, amely zökkenőmentesen integrálódik AMD-alapú rendszerébe. Megbízható és kompatibilis teljesítménynövelés az építéshez.\r\n\r\nPlug N Play - Automatikus overlock 2666 MHz-ig\r\n\r\nAz egyszerű és könnyű Plug N Play frissítés, a Kingston FURY Beast DDR4 automatikusan túlhajtja a rendszer BIOS által megengedett legmagasabb sebességre. ', 10, 28700, 0, '837367293.kingston-fury-beast-16gb-2x8gb-ddr4-3200mhz-kf432c16bbk2-16.jpg', 'memória'),
('KVR16N11/8', 'Kingston ValueRAM 8GB DDR3 1600MHz', 'Típus	PC memória\r\nKapacitás	8 GB\r\nKiszerelés	1x8GB\r\nMemória típusa	DDR3\r\nSebesség	1600 MHz\r\nTöbbcsatornás kiszerelés	Single-channel kiszerelés\r\nMemóriakésleltetés 	CL 11\r\nHűtőborda 	Nincs\r\nLED megvilágítás	Nincs\r\nFeszültség	1.5 V', ' Leírás:\r\n\r\nA Kingston ValueRAM termékvonala az ipar legszigorúbb előírásainak is megfelel. Folyamatosan, külső, nagy laborok által is tesztelve és elismerésüket elnyerve.\r\n\r\nA DDR3 memória optimális választás a rendszere teljesítmény növelésére. Nemcsak a memóriaméret változást fogja pozitívan érzékelni, de a gyors 1600MHz frekvencia működését is.\r\n\r\nMinden Kingston memória a legújabb vezető gyártási technológia eredménye. Stabilitás, gyorsaság, 100%-os kompatibilitás jellemzi.\r\n\r\nKompatibilitás\r\n\r\n    ASRock - Alaplap 990FX Extreme3\r\n    ASRock - Alaplap 990FX Extreme4\r\n    ASRock - Alaplap B75 Pro3\r\n    ASRock - Alaplap B75 Pro3-M\r\n    ASRock - Alaplap B75M\r\n    ASRock - Alaplap B75M-ITX\r\n    ASRock - Alaplap Fatal1ty 990FX Professional\r\n    ASRock - Alaplap Fatal1ty P67 Performance\r\n    ASRock - Alaplap Fatal1ty P67 Professional\r\n    ASRock - Alaplap Fatal1ty X79 Professional\r\n    ASRock - Alaplap Fatal1ty Z68 Professional Gen3\r\n    ASRock - Alaplap Fatal1ty Z77 Performance', 10, 17300, 0, '118703124.kingston-valueram-8gb-ddr3-1600mhz-kvr16n11-8.jpg', 'memória'),
('LG-G305-LS', 'Logitech G305 ', 'Egér típusa	Optikai\r\nVezeték nélküli	igen\r\nEgér csatlakoztatása	USB\r\nÉrzékenység	12000 DPI\r\nGombok száma	6 db', 'HERO ÉRZÉKELŐ\r\n\r\nA HERO a Logitech G által tervezett, forradalmian új optikai érzékelő kategóriájában a legjobb teljesítménnyel és akár 10-szer takarékosabb energiafelhasználással (az előző generációhoz viszonyítva). A HERO érzékelő kivételes pontosságot és állandó teljesítményt nyújt 200–12 000 DPI tartományban simítás, gyorsítás vagy szűrés nélkül. A G305 akár 5 profilt is tud menteni 5 DPI-szinttel, amelyek mindegyike a beépített memóriában található.\r\n\r\nA MÁGIKUS GÁZKAR\r\n\r\nA HERO valódi áttörést jelent az innováció terén az érzékelőtechnológiában a forradalmi teljesítményével és hatékonyságával. Egyedülálló abból a szempontból, hogy nagy teljesítményű és hosszan tartó játékhoz készült vezeték nélküli egerek új generációjának biztosít teret.\r\n\r\n10-SZERES HATÉKONYSÁG\r\n\r\nA HERO egy intelligens energiagazdálkodási rendszert használ, hogy folyamatosan az egér sebességéhez illessze az érzékelési gyakoriságot. Ez lehetővé teszi a teljesítmény növelését, a folyamatos felügyeletet, illetve minimalizálja az energiafelhasználást. Ez megegyezik 250 órányi üzemidővel.\r\n\r\n*Az üzemidő a felhasználótól, az elem lemerülési karakterisztikájától és a számítás feltételeitől függően változhat 1 db AA ceruzaelemmel.\r\n\r\n1 ezredmásodperces VEZETÉK NÉLKÜLI ÁTVITEL\r\n\r\nA Logitech G mérnökei kidolgoztak egy teljes körű technológiai optimalizálást az érzékelőktől a belső vezérlőprogramig, az áramköröktől az antennáig. Tapasztalt csapatunk minden összetevőt tesztelt és átdolgozott, a leglassabb láncszemre összpontosítva, amíg végül semmi nem bizonyult lassúnak.', 5, 14990, 15, '1090014.logitech-g305.jpg', 'egér'),
('MEMPEK1J016GA01', 'Intel Optane 16GB M.2 PCIe', 'Kapacitás	16 GB\nNAND flash típusa 	3D XPoint\nMaximális SSD olvasási sebesség	900 MB/s\nMaximális SSD írási sebesség	145 MB/s\nHűtőborda	Nincs\nPCI-e generáció	3.0\nCsatlakozók	\nPCI-e\nMéretek\nMélység	80 mm\nKialakítás	M.2', 'Növeld mag a meg a HDD vagy az SSD teljesítményét az Intel Optane Memory M10 lemezzel. Ennek köszönhetően nemcsak az operációs rendszer indítása és az adatátvitel gyorsul, de az igényes alkalmazások, grafikus szerkesztőprogramok vagy játékok futása is gyorsul.\n\nFő előnye a 3D XPoint memóriák használata, amely akár 1000-szer gyorsabb is lehet a NAND memóriáktól, és teljesítménye nem csökken az idő múlásával. Ráadásul az egyes műveletek válaszidejét nanoszekundumban mérhetjük, ami csak a töredéke annak, amit a felhasználók megszoktak.\n\nAz Intel Optane Memory M10 lemezben azt is értékelni fogod, hogy a 3D Xpoint nem volatilis, vagyis az adatok nem vesznek el a tápfeszültség hirtelen megszűnésekor. ', 15, 1990, 0, '504554723.intel-optane-16gb-m-2-pcie-mempek1j016ga01.jpg', 'memória-lemez'),
('P38454-B21', 'HP 32GB DDR4 3200MHz', 'Típus	PC memória\r\nKapacitás	32 GB\r\nKiszerelés	1x32GB\r\nMemória típusa	DDR4\r\nSebesség	3200 MHz\r\nTöbbcsatornás kiszerelés	Single-channel kiszerelés\r\nHűtőborda 	Nincs\r\nLED megvilágítás	Nincs\r\nFeszültség	1.20 V', 'Ha szenvedélyesen rajongsz a informatikai és elektromostermékekért, és szeretsz lépést tartani a technológiával, ne maradj le a legkisebb részletekről sem, vásárold meg RAM Memória HPE P38454-B21 32 GB DDR4 32 GB DDR4-et verhetetlen áron. Belső memória: 32 GBDDR4Sebesség: 3200 MHzFormátum: 1 x 32 GBFeszültség: 1,2 VKapcsolat: 288-pin DIMMTípus: DDR4Kompatibilis: PC/Server ', 10, 306150, 0, '932941932.hp-32gb-ddr4-3200mhz-p38454-b21.jpg', 'memória'),
('ROG-STX-B550-F-G', 'ASUS ROG STRIX B550-F GAMING Alaplap', 'CPU Foglalat: Socket AM4\nChipset: AMD B550\nProcesszor gyártó: AMD\nMemória típusa: DDR4\nSzerver alaplap: Nem\nMax. memória mérete: 128 GB\nIntegrált hangkártya: Van\nHangkártya csatorna: 7.1\nDigitális hangkimenet: Optikai\nVezeték nélküli hálózat: Van\nBluetooth: Nincs\nRAID vezérlő: Van\nRAID szintek: 0, 1, 10\nMéret szabvány: ATX\nAlaplap mérete: 305 x 244', 'Gyártó: ASUS\nModell: ROG Strix B550-F Gaming\n\nMűszaki adatok:\n\nChipset típus:B550,\nCrossfire támogatás:Igen,\nD-Sub kimenet:Nem,\nDisplayPort kimenet:1,\nDVI-D kimenet:Nem,\nDVI-I kimenet:Nem,\neSATA kimenet:0,\nFormátum:ATX,\nHálózati csatlakozás:1 x 100/1000/2500 Mb/s,\nHDMI kimenet:1,\nm. 2 csatlakozó:2,\nMaximum memória (GB):128,\nMemória foglalat:DDR4,\nMemória foglalatok száma:4,\nMemória sebesség (Mhz):5100,\nMini PCI-E:Nem,\nmSATA csatlakozó:Nem,\nPCI csatlakozó:0,\nPCI-e verzió:3.0, 4.0,\nPCI-E x1 csatlakozó:3,\nPCI-e x16 csatlakozó:2,\nPCI-e x4 csatlakozó:0,\nProcesszor foglalat:AMD AM4,\nPS/2 csatlakozó:0,\nRaid:0,1, 10,\nS/PDIF optikai kimenet:Nem,\nSATA 2 csatlakozó:0,\nSATA 3 csatlakozó:6,\nSLI támogatás:Nem,\nTáp csatlakozó (pin):24+8+4,\nUSB 2.0 kimenet:2,\nUSB 3.0 kimenet:4,\nUSB 3.1 kimenet:2,\nUSB Type-C:0,\nVezeték nélküli hálózat:Nem', 12, 69990, 8, '698708712.asus-rog-strix-b550-f-gaming.jpg', 'alaplap'),
('RX6600MECH2X8G', 'MSI Radeon RX 6600 8GB GDDR6', 'Csatolófelület 	PCI-Express\nVideo chipset	AMD Radeon\nVideo chipset termékcsalád	RX 6600\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	2491 MHz\nGrafikus memória sebessége	14000 MHz\nMemória mérete 	8 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	128 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	AMD Radeon\nVideo chipset termékcsalád	RX 6600\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	2 darab\nGrafikus chip sebessége	2491 MHz\nGrafikus memória sebessége	14000 MHz\n\nMemória\n\nMemória mérete 	8 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	128 bit\n\nTovábbi tulajdonságok\n\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12\nOpenGL	4.6\nTápcsatlakozó	1 x 8-pin\nFogyasztás	132 W\nAjánlott tápegység	500 W\nLite Hash Rate 	Nem\n\nAlkalmazott technológiák\n\nAMD Eyefinity\nAMD HD3D\nAMD PowerPlay\n\nCsatlakozók\n\nHDMI\nDisplayPort\n\nMéretek\n\nSzélesség	125 mm\nHosszúság	235 mm\nVastagság	46 mm', 31, 160280, 5, '896354220.msi-radeon-rx-6600-8gb-gddr6-128bit-rx-6600-mech-2x-8g.jpg', 'videokártya'),
('RZ01-03250100-R3M1', 'Razer Viper Mini', 'Egér típusa	Optikai\r\nVezeték nélküli	nem\r\nEgér csatlakoztatása	USB\r\nÉrzékenység	8500 DPI\r\nGombok száma	6 db', 'Ultrakönnyű súlyú kialakítás\r\nA kétkezes váz kialakítása tovább csökkenti a termék súlyát, így gyorsabb irányítás részese lehet, miközben az egér strapabírósága nem csökken. Kis és közepes kéz méretű gamerek számára ajánlott és kiváló azok számára, akik claw, vagy fingertip grip stílusban használják egerüket.\r\n\r\nRazer optikai egér switch\r\nMinden kattintás fénysebességgel történik. A Razer™ Optikai Egér Switch az infravörös fénysugarat használja a kattintásnál, amelynek eredménye a 0.2 milliszekundumos piacvezető reakcióidő.\r\n\r\nRazer Speedflex kábel\r\nAnnak érdekében, hogy minden esetben versenyelőnyt biztosítson Önnek, a Razer olyan egérkábelt tervezett, amely lehetővé teszi a simább egér csúsztatást. A Razer Viper Mini rendkívül rugalmas Razer™ Speedflex kábellel rendelkezik, akadálytalan irányítást biztosítva minimális húzással.', 6, 14900, 0, '675206262.razer-viper-mini-rz01-03250100-r3m1.jpg', 'egér'),
('S28AG700NU', 'Samsung Odyssey G7', 'Típus	LED monitor\r\nPanel típusa	IPS\r\nÍvelt kijelző	nem\r\n3D monitor	nem\r\nÉrintőképernyő	nem\r\nKépátló	28 inch\r\nKéparány	16:9\r\nFelbontás	3840 x 2160\r\nVálaszidő	1 ms\r\nFényerő	300 cd/m2\r\nStatikus kontraszt	1000:1\r\nBetekintési szög	178 °\r\nKépfrissítési frekvencia	144 Hz', 'Hiper valósághű világok a képernyődön\r\n\r\nFedj fel minden részletet a maximális tisztaságért! Az FHD pixelsűrűségének 4-szeresét hozó képernyővel új szinten élheted meg a játékokat. Az IPS panel tiszta színeket és széles 178º-os látószöget biztosít, bármely nézőpontból. Több képponttal és nagyobb mélységgel a játékok közelebb állnak a valósághoz, mint korábban.\r\n\r\nFényesen ragyogó részletek\r\n\r\nFedd fel a teljes képet! A HDR400 nagyobb kontrasztot nyújt mélyebb feketével és világosabb fehérekkel, hogy segítsen észrevenni a sötétben megbújó ellenségeket és titkokat. Még a sötét jelenetekben is, minden részlet ragyogóan fényes.\r\n\r\n144Hz képernyő frissítési ráta és 1 ms válaszidő\r\n\r\nGyőzz le minden ellenséget, akár száguldozó sebességgel is! A 144Hz képernyő frissítési ráta, ami a legmagasabb a 4K gaming monitorok esetében, minimalizálja a késést gördülékeny akcióért. - Mindezt kiemelkedő UHD részletességgel. Vesd rá magad az ellenségekre, amint meglátod őket az 1 ms-es válaszidővel és elmosódásmentes megjelenítéssel, szellemképhatás nélkül!\r\n\r\nGyőztes reflexek\r\n\r\nRagadd meg az irányítást! A hihetetlenül alacsony 2ms bemeneti késés elhozza a soha nem tapasztalt válaszpontosságot az agilis ellenségek elkapása érdekében. Olyan gyors, hogy az akció azonnal elkezdődik, ahogy bekapcsolod a képernyőt, és gyakorlatilag nincs késés a perifériák és a játék között\r\n\r\nZavartalan játékmenet\r\n\r\nZökkenőmentes hipergyors játékmenet. A G-Sync kompatibilitása folyamatosan szinkronizálja a GPU-t és a panelt, hogy kiküszöbölje az elakadást, a képernyőn megjelenő késést és a kép szaggatását. A gyors és bonyolult játékjelenetek stabilak és akadozásmentesek, így az AMD FreeSync Premium Pro-val megőrizheted a versenyelőnyöd.', 5, 231900, 0, '847583607.samsung-odyssey-g7-s28ag700nu.jpg', 'monitor'),
('SPG070', 'SPC Gear GK630K', 'Billentyűzet csatlakoztatása	USB\r\nVezeték nélküli	Nem\r\nMultimedia billentyűzet 	Nem\r\nHáttérvilágítás	Van\r\nMechanikus 	Igen\r\nNumerikus billentyűzet	Nincs', 'Gyártó: SPC Gear\r\nModell: GK630K (SPG070)\r\n\r\nTulajdonságok:\r\n\r\n    Mechanikus kapcsolók\r\n    88 gombos kivitel\r\n    RGB világítás\r\n    Kábelhossz: 1.8 m\r\n    Anti-ghosting\r\n    Méretek: 400 x 190 x 50 mm\r\n    Súly: 915 g\r\n', 10, 17300, 5, '754120560.spc-gear-gk630k-spg070.jpg', 'billentyűzet'),
('SSDPEKNW010T9X1', 'Intel 665p 1TB', 'Kapacitás	1000 GB\r\nNAND flash típusa 	QLC\r\nMaximális SSD olvasási sebesség	2000 MB/s<br>\r\nMaximális SSD írási sebesség	1925 MB/s<br>\r\nÍrástűrés (TBW) 	300 TBW<br>\r\nHűtőborda	Nincs<br>\r\nPCI-e generáció	3.0<br><br>\r\nCsatlakozók	<br>\r\nPCI-e<br>\r\nMéretek<br>\r\n	<br>\r\nSzélesség	80 mm<br>\r\nMagasság	3.5 mm<br>\r\nMélység	22 mm<br>\r\nTömeg	80 g<br>\r\nKialakítás	M.2<br>', '\n    Világítás: Nem\n    Hűtőborda: Nem\n    Típus: Belső\n    Méret: M.2 2280\n    Csatlakozás: M.2 PCIe\n    Tároló kapacitás: 1000 GB\n    SSD max írás: 1925 MB/s\n    SSD max olvasás: 2000 MB/s\n    TBW: 300 TB\n    Technológia: QLC\n    Kiszerelés: Csak a meghajtó\n', 5, 74390, 5, '697001616.intel-665p-1tb-ssdpeknw010t9x1.jpg', 'SSD'),
('SSDPEKNW020T8X1', 'Intel 660p Series 2TB M.2', 'Kapacitás	2000 GB\nNAND flash típusa 	QLC\nMaximális SSD olvasási sebesség	1800 MB/s\nMaximális SSD írási sebesség	1800 MB/s\nÍrástűrés (TBW) 	400 TBW\nHűtőborda	Nincs\nPCI-e generáció	3.0\n', 'smerje meg a ma tárolási szükségleteit, és készüljön fel a holnap növekvő igényeire az Intel 660p sorozattal, amely az Intel QLC 3D NAND technológiára épül.  \nAz Intel SSD 660p az első QLC alapú kliens PCIe SSD az iparágban, folytatva az Intel vezető szerepét a flash-cella technológiában és a minőségi gyártásban.  \n\n. PCIe teljesítmény elérhető áron <br>\nAz innovatív Intel QLC technológiával az Intel SSD 660p magasabb kapacitást kínál alacsonyabb áron, mint a TLC alapú változatok. A PCIe segítségével az SSD 660p átlépi a SATA-t és korlátait, hogy akár 2TB-ot nyújtson egyetlen meghajtóban  \n\n. Kétszeres kapacitás változatlan méretben \nEzek a kliens-SSD-k több adatot tárolnak mint a TLC alapú eszközök, lehetővé téve az akár 2-szeres kapacitást azonos méretben. A vékony M. 2 80mm formai szabvány tökéletessé teszi notebook-okhoz, asztali gépekhez, és mobileszközökhöz.   ', 10, 79800, 0, '576207651.intel-660p-series-2tb-m-2-ssdpeknw020t8x1.jpg', ''),
('SSR-650LM', 'Seasonic Core GM 650W Gold', 'Tápegység típusa	Fél moduláris tápegység\nTápegység teljesítménye	650 W\nHatásfok	80+ Gold\nPFC	Aktív\nVentilátor mérete	120 mm\nMax. áramfelvétel +3,3V	20 A\nMax. áramfelvétel +5V	20 A\nMax. áramfelvétel +12V1	54 A\nMax. áramfelvétel -12V	0.3 A\nTápkapcsoló 	Van\n110V kapcsoló 	Nincs\n	\nFDD csatlakozó 	Nincs\nHDD csatlakozó 	3\nSATA csatlakozó 	6\nPCI-Express csatlakozó 	4', 'A CORE egy vadonatúj sorozat, amely kiegészíti a Seasonic termékkínálatát. A 80 PLUS® Gold minősítésű CORE sorozat háromféle kábelezéssel kapható: a teljesen moduláris CORE GX, a félig moduláris CORE GM, és a rögzített kábelezésű CORE GC változatban. A Seasonic Smart és a Silent Fan Control (csendes ventilátorvezérlő) automatikusan beállítja a ventilátor sebességét a tápegység belső hőmérsékletétől függően. A TUF Gaming Alliance részeként a CORE sorozat a tökéletes egység gaming PC-dhez.\n\n80 PLUS® GOLD\n\nA CORE GM sorozat 50% terhelés melletti 90% hatékonyságával eléri a 80 PLUS® Gold minősítést\n\nFélig moduláris kábelek\n\nNéhány kábel állandóan a tápegységhez csatlakozik (a 24 tűs és a 8 tűs ATX tápkábelek), a többi kábel pedig felhasználható a többi komponens csatlakoztatására\n\nS2FC - okos és csendes ventilátorvezérlő\n\nAz intelligens hőáramkör úgy lett tervezve, hogy megtalálja az optimális egyensúlyt az alkatrészek hűtésének és a tápegység lehető legcsendesebb működésének szükségessége között ', 5, 31790, 10, '611929647.seasonic-core-gm-650w-gold-ssr-650lm.jpg', 'tápegység'),
('SSR-850PX', 'Seasonic FOCUS PLUS 850W Platinum', 'Tápegység típusa	Moduláris tápegység\nTápegység teljesítménye	850 W\nHatásfok	80+ Platinum\nPFC	Aktív\nVentilátor mérete	120 mm\nMax. áramfelvétel +3,3V	20 A\nMax. áramfelvétel +5V	20 A\nMax. áramfelvétel -12V	0.3 A\nTápkapcsoló 	Van\n110V kapcsoló 	Nincs\n	\nFDD csatlakozó 	1\nHDD csatlakozó 	5\nSATA csatlakozó 	10\nPCI-Express csatlakozó 6', 'A teljesen moduláris, 80 PLUS® Platinum minősítésű FOCUS + Platinum 850W-os tápegység az egyenáramú DC-DC átalakító koncepcióra épül, és a teljesítmény jellemzői a szűk feszültség szabályozásával meggyőzőek.<br>\r\n\r\nEzek a tápegységek magas hőmérsékletű japán kondenzátorokat használnak a szélsőséges körülmények közötti stabilitás biztosítása érdekében.\r\nA stabilitás és a figyelemre méltó kimeneti jellemzők mellett ez a készülék a legmagasabb teljesítménysűrűséggel rendelkezik kategóriájában.<br>\r\n\r\nA csendesség iránt rajongók nagyra értékelik a Seasonic Hybrid Silent Fan Control rendszert, amely az iparág első háromfokozatú, fejlett termikus vezérlése az optimális egyensúly elérése érdekében a csend és a hűtés között.<br> ', 3, 66590, 0, '457877415.seasonic-focus-plus-850w-platinum-ssr-850px.jpg', 'tápegység'),
('TUF-RTX3060-O12G-V2-GAMING', 'ASUS GeForce RTX 3060 12GB GDDR6 V2 OC LHR', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	RTX 3060\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	3 darab\nGrafikus chip sebessége	1882 MHz\nGrafikus memória sebessége	15000 MHz	\nMemória mérete 	12 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	192 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	RTX 3060\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	3 darab\nGrafikus chip sebessége	1882 MHz\nGrafikus memória sebessége	15000 MHz\n\nMemória\n	\nMemória mérete 	12 GB\nMemória típusa	GDDR6\nMemória sávszélesség 	192 bit\n\nTovábbi tulajdonságok\n	\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12\nOpenGL	4.6\nTápcsatlakozó	1 x 8-pin\nAjánlott tápegység	750 W\nLite Hash Rate 	Igen<br>\nAlkalmazott technológiák\n	\nnVidia CUDA\nnVidia PhysX \nnVidia Pure Video HD\nnVidia 3D Vision \nGeForce RTX VR Ready\n \nCsatlakozók\nHDMI\nDisplayPort\n \nMéretek\n	\nSzélesség	143 mm\nHosszúság	301 mm\nVastagság	54 mm', 8, 299990, 0, '829085862.asus-geforce-rtx-3060-12gb-gddr6-v2-oc-lhr-tuf-rtx3060-o12g-v2-gaming.jpg', 'videokártya'),
('TUF-RTX3070TI-O8G-GAMING', 'ASUS GeForce RTX 3070 Ti OC 8GB GDDR6X ', 'Csatolófelület : PCI-Express\n    Video chipset: Nvidia GeForce\n    Video chipset termékcsalád: RTX 3070 Ti\n    Hűtés típusa : Aktív hűtés\n    Ventilátorok száma: 3 darab\n    Grafikus chip sebessége: 1815 MHz\n    Grafikus memória sebessége: 19000 MHz\n    Memória mérete : 8 GB\n    Memória típusa: GDDR6X Memória sávszélesség: 256 bit', 'Csatolófelület 	PCI-Express\nVideo chipset	Nvidia GeForce\nVideo chipset termékcsalád	RTX 3070 Ti\nHűtés típusa 	Aktív hűtés\nVentilátorok száma	3 darab\nGrafikus chip sebessége	1815 MHz\nGrafikus memória sebessége	19000 MHz\n\nMemória\n	\nMemória mérete 	8 GB\nMemória típusa	GDDR6X\nMemória sávszélesség 	256 bit\n\nTovábbi tulajdonságok\n	\nMaximális felbontás	7680 x 4320 pixel\nDirectX	12\nOpenGL	4.6\nTápcsatlakozó	2 x 8-pin\nAjánlott tápegység	750 W\nLite Hash Rate 	Nem\nAlkalmazott technológiák	\nnVidia CUDA\nnVidia PhysX\nnVidia Pure Video HD\nnVidia 3D Vision\nGeForce RTX VR Ready\n \nCsatlakozók\n\nHDMI\nDisplayPort\n \nMéretek\n	\nSzélesség	126.9 mm\nHosszúság	299.9 mm\nVastagság	51.7 mm', 30, 362000, 10, '831270750.asus-geforce-rtx-3070-ti-oc-8gb-gddr6x-256bit-tuf-rtx3070ti-o8g-gaming.jpg', 'videokártya');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `vasarlasok`
--

CREATE TABLE `vasarlasok` (
  `id` int(11) NOT NULL,
  `felhasznalonev` varchar(200) NOT NULL,
  `termek` text NOT NULL,
  `datum` date NOT NULL,
  `ar` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `vasarlasok`
--

INSERT INTO `vasarlasok` (`id`, `felhasznalonev`, `termek`, `datum`, `ar`) VALUES
(4, 'admin1', 'ASUS ROG STRIX B550-F GAMING Alaplap', '2022-05-03', 64391),
(5, 'admin1', 'AMD Ryzen 5 5600X 6-Core 3.7GHz AM4 Box with fan and heatsink', '2022-05-03', 99500),
(6, 'cspisti', 'MSI Radeon RX 6600 8GB GDDR6', '2022-05-03', 152266),
(7, 'admin1', 'ASUS GeForce RTX 3070 Ti OC 8GB GDDR6X ', '2022-05-03', 362000),
(8, 'admin1', 'AMD Ryzen 3 1200 AF 4-Core 3.1GHz АМ4 Tray', '2022-05-03', 31445),
(9, 'admin1', ' GIGABYTE GeForce GTX 1660 Ti OC 6GB', '2022-05-03', 146294),
(10, 'kzoli', ' GIGABYTE GeForce GTX 1660 Ti OC 6GB', '2022-05-03', 146294),
(11, 'kzoli', 'ASRock H470M-HDV Alaplap', '2022-05-03', 21100),
(12, 'MBela1', 'AOC 24G2U Monitor ', '2022-05-15', 64700);

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `felhasznalok`
--
ALTER TABLE `felhasznalok`
  ADD PRIMARY KEY (`id`) USING BTREE;

--
-- A tábla indexei `termekek`
--
ALTER TABLE `termekek`
  ADD PRIMARY KEY (`cikkszam`);

--
-- A tábla indexei `vasarlasok`
--
ALTER TABLE `vasarlasok`
  ADD PRIMARY KEY (`id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `felhasznalok`
--
ALTER TABLE `felhasznalok`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT a táblához `vasarlasok`
--
ALTER TABLE `vasarlasok`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
